name: R
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-irkernel
  - bioconductor-biostrings
  - r-devtools=2.3.2
  - r-git2r=0.27.1
  - r-glue=1.4.1
  - r-here=1.0.1
  - r-knitr=1.33
  - r-lintr=2.0.1
  - r-optparse=1.6.6
  - r-plotly=4.9.2.1
  - r-rcpproll=0.3.0
  - bioconductor-rhdf5
  - r-rmarkdown=2.7
  - r-roxygen2=7.1.1
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - r-scales=1.1.1
  - r-shiny=1.5.0
  - bioconductor-shortread
  - r-styler=1.3.2
  - r-testthat=3.0.1
  - r-tidyverse=1.3.0
  - r-withr=2.3.0
  - r-yaml=2.2.1
